toml
[project]
name = "my_awesome_lib"
version = "1.0"
description = "my_awesome_lib lab 3"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["my_awesome_lib"]
link = https://github.com/Aksymand1/WSB-Python/tree/main/zadanie_3